#!/usr/bin/env python3
"""Build the policymemo.ai site pages from site/.

Posts live in site/blog/posts/*.md, each with a short front matter block:

    ---
    title: Why policymemo.ai asks before it writes
    date: 2026-10-06
    category: why            # why | skills | guides | updates
    skill: problem           # only for posts in the skills series
    summary: One sentence for the index and for link previews.
    draft: true              # optional; drafts are never published
    ---

This writes docs/blog/index.html and one docs/blog/<slug>.html per published
post (the slug is the file name), plus two Atom feeds: feed.xml (every post)
and, once an updates post exists, feed-updates.xml (product updates only). The
feeds are not linked from the page; feed readers find them from the <head>
tags. It also updates the homepage between its blog markers: a Blog link in the
nav and footer, and a "Read the post" link on each skill card, all of which
stay empty until something is published, so the site never shows an empty blog.

It also writes the site's other generated pages, all in the same chrome:
docs/install/ from site/install/, docs/beta/ from site/beta/ (form links and contact
details come from site/beta/config.json), and docs/updates/ from site/updates/changelog.md.

    python3 tools/build-site.py              # publish
    python3 tools/build-site.py --drafts OUT # preview everything, drafts included, into OUT

Requires the `markdown` package (pip install markdown).
"""
import datetime
import html
import json
import pathlib
import re
import sys

import markdown

ROOT = pathlib.Path(__file__).resolve().parent.parent
POSTS = ROOT / "site" / "blog" / "posts"
CSS = ROOT / "site" / "blog" / "blog.css"
OUT = ROOT / "docs" / "blog"
HOME = ROOT / "docs" / "index.html"
INSTALL = ROOT / "site" / "install"
INSTALL_OUT = ROOT / "docs" / "install"
BETA = ROOT / "site" / "beta"
BETA_OUT = ROOT / "docs" / "beta"
CHANGELOG = ROOT / "site" / "updates" / "changelog.md"
UPDATES_OUT = ROOT / "docs" / "updates"
ICONS = ROOT / "docs" / "icons"
MASCOT = ROOT / "docs" / "mascot.svg"
# Categories in use among published posts. Labels and filters show only once there are two,
# and the updates feed only once there is an updates post.
USED = []
GENERATED = "<!-- generated by tools/build-site.py; edit site/ or the script, not this file -->"

CATEGORIES = {"why": "Why it works", "skills": "The skills", "guides": "Guides", "updates": "Updates"}
# Skill slug, card title on the homepage, icon file.
SKILLS = [
    ("problem", "Problem", "problem"), ("stakeholders", "Stakeholders", "stakeholders"),
    ("evidence", "Evidence", "evidence"), ("options", "Options", "options"),
    ("criteria", "Criteria", "criteria"), ("outcomes", "Outcomes", "uncertainty"),
    ("trade-offs", "Trade-offs", "tradeoffs"), ("decide", "Decide", "decision"),
    ("story", "Story", "story"),
]
# Where the CIVICWORKS link in the nav goes: the page on CIVICWORKS for writing about policymemo.ai.
# The build also writes it into the homepage nav, so this is the only place to change it.
CIVICWORKS_NAV = "https://civicworks.substack.com/s/policymemoai"
# Every CIVICWORKS link opens in a new tab, so policymemo.ai stays open behind it.
CIVICWORKS_NAV_LINK = (f'<a class="plain dot-link" href="{CIVICWORKS_NAV}" target="_blank" rel="noopener" '
                       'aria-label="CIVICWORKS (opens in a new tab)">CIVICWORKS<span class="new-dot" aria-hidden="true"></span></a>')
FEEDBACK = "mailto:jack@civicworks.co?subject=policymemo.ai%20feedback"
SITE = "https://policymemo.ai"
AUTHOR = ("Jack Strachan", "jack@civicworks.co")
FEEDS = [("feed.xml", "Notes · policymemo.ai", None),
         ("feed-updates.xml", "Product updates · policymemo.ai", "updates")]


def read_post(path):
    text = path.read_text(encoding="utf-8")
    m = re.match(r"---\n(.*?)\n---\n(.*)", text, re.S)
    if not m:
        raise SystemExit(f"{path.name}: missing front matter")
    meta = {}
    for line in m.group(1).splitlines():
        if ":" in line:
            k, v = line.split(":", 1)
            meta[k.strip()] = v.split(" #", 1)[0].strip()
    for key in ("title", "date", "category", "summary"):
        if not meta.get(key):
            raise SystemExit(f"{path.name}: front matter needs '{key}'")
    if meta["category"] not in CATEGORIES:
        raise SystemExit(f"{path.name}: category must be one of {', '.join(CATEGORIES)}")
    if meta.get("skill") and meta["skill"] not in {s[0] for s in SKILLS}:
        raise SystemExit(f"{path.name}: unknown skill '{meta['skill']}'")
    meta["date_obj"] = datetime.date.fromisoformat(meta["date"])
    meta["draft"] = meta.get("draft", "").lower() == "true"
    meta["slug"] = path.stem
    meta["body"] = markdown.markdown(m.group(2), extensions=["extra", "smarty"])
    words = len(re.sub(r"<[^>]+>", " ", meta["body"]).split())
    meta["minutes"] = max(1, round(words / 220))
    return meta


def nice_date(d):
    return f"{d.day} {d.strftime('%B %Y')}"


def svg_inline(path, cls, prefix):
    s = path.read_text(encoding="utf-8")
    s = re.sub(r"<\?xml.*?\?>", "", s).strip()
    s = re.sub(r"<title>.*?</title>", "", s)
    s = s.replace('id="pm-', f'id="{prefix}').replace("url(#pm-", f"url(#{prefix}")
    return s.replace("<svg ", f'<svg class="{cls}" aria-hidden="true" ', 1)


def show_cats():
    return len(USED) > 1


def cat_label(p, before="", after=""):
    return f'{before}<span class="cat">{CATEGORIES[p["category"]]}</span>{after}' if show_cats() else ""


def updates_link(home):
    if "updates" not in USED:
        return ""
    return f'<link rel="alternate" type="application/atom+xml" title="Product updates · policymemo.ai" href="{home}blog/feed-updates.xml">\n'


def page(title, description, body, css, home, depth_note="", current="notes"):
    def cur(name):
        return ' aria-current="page"' if current == name else ""
    mascot = svg_inline(MASCOT, "logo", "lg-").replace('fill="#1c1b18"', 'fill="currentColor"')
    return f"""<!doctype html>
{GENERATED}
<html lang="en-GB">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="color-scheme" content="light">
<title>{html.escape(title)}</title>
<meta name="description" content="{html.escape(description)}">
<meta property="og:title" content="{html.escape(title)}">
<meta property="og:description" content="{html.escape(description)}">
<meta property="og:image" content="https://policymemo.ai/og.png">
<meta name="twitter:card" content="summary_large_image">
<link rel="icon" href="{home}favicon.svg" type="image/svg+xml">
<link rel="alternate" type="application/atom+xml" title="Notes · policymemo.ai" href="{home}blog/feed.xml">
{updates_link(home)}<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght,SOFT@9..144,300..600,0..100&family=Geist:wght@400..600&display=swap" rel="stylesheet">
<style>
{css}
</style>
</head>
<body>
<header class="top">
  <div class="wrap bar">
    <a class="brand" href="{home}" aria-label="policymemo.ai home">{mascot}</a>
    <nav aria-label="Main">
      <a class="plain" href="{home}#what">What it does</a>
      <a class="plain" href="{home}#how">How it behaves</a>
      <a class="plain keep" href="{home}updates/"{cur("updates")}>Updates</a>
      {CIVICWORKS_NAV_LINK}
      <a class="btn primary small" href="{home}beta/">Beta access</a>
    </nav>
  </div>
</header>
<main>
{body}
</main>
<footer>
  <div class="wrap row">
    <span>policymemo.ai · beta 0.1.2 · by <a href="https://civicworks.substack.com" target="_blank" rel="noopener">CIVICWORKS</a></span>
    <nav aria-label="Footer">
      <a href="{home}">Home</a>
      <a href="{home}beta/">Beta</a>
      <a href="{home}updates/">Updates</a>
      <a href="{home}blog/">Notes</a>
      <a href="{home}install/">Install</a>
      <a href="{FEEDBACK}">Feedback</a>
      <a href="https://github.com/Policy-Analysis-Tools-for-Everyone/Alpha">GitHub</a>
    </nav>
  </div>
</footer>
<script>
(function () {{
  var reduce = window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  var els = Array.prototype.slice.call(document.querySelectorAll('[data-rise]'));
  if (reduce || !('IntersectionObserver' in window)) return;
  els.forEach(function (el) {{ if (el.getBoundingClientRect().top > window.innerHeight) el.classList.add('pre'); }});
  var io = new IntersectionObserver(function (es) {{
    es.forEach(function (e, k) {{ if (e.isIntersecting) {{ io.unobserve(e.target); setTimeout(function () {{ e.target.classList.remove('pre'); }}, k * 90); }} }});
  }}, {{ threshold: 0.2 }});
  els.forEach(function (el) {{ io.observe(el); }});
  var chips = Array.prototype.slice.call(document.querySelectorAll('.filters button'));
  chips.forEach(function (c) {{
    c.addEventListener('click', function () {{
      var cat = c.getAttribute('data-cat');
      chips.forEach(function (x) {{ x.setAttribute('aria-pressed', x === c ? 'true' : 'false'); }});
      document.querySelectorAll('.post-row').forEach(function (r) {{ r.hidden = cat !== 'all' && r.getAttribute('data-cat') !== cat; }});
    }});
  }});
}})();
</script>
</body>
</html>
"""


def build_index(posts, css, home):
    by_skill = {p["skill"]: p for p in posts if p.get("skill")}
    rows = "".join(
        f'<li class="post-row" data-cat="{p["category"]}" data-rise><a href="{p["slug"]}.html">'
        f'<span class="meta">{cat_label(p, after=" · ")}{nice_date(p["date_obj"])}</span>'
        f'<span class="t">{html.escape(p["title"])}</span><span class="s">{html.escape(p["summary"])}</span></a></li>'
        for p in posts)
    latest = (f'<ul class="posts">{rows}</ul>' if posts else
              '<p class="empty">The first post is on its way. In the meantime, <a href="' + home + '">see what policymemo.ai does</a>.</p>')
    cards = ""
    for slug, title, icon in SKILLS:
        p = by_skill.get(slug)
        art = svg_inline(ICONS / f"{icon}.svg", "icon", f"sk-{slug}-")
        status = (f'<a class="read" href="{p["slug"]}.html">Read · {nice_date(p["date_obj"])}</a>' if p
                  else '<span class="soon">Coming soon</span>')
        cards += f'<li class="{"live" if p else "planned"}" data-rise>{art}<h3>{title}</h3>{status}</li>'
    # The series grid appears once the first skill post is published.
    series = f"""<section class="wrap series" aria-labelledby="series">
  <h2 id="series">One post for each skill</h2>
  <p class="intro">Each post covers what the skill does, the method behind it, and what it looks like on a real problem.</p>
  <ul class="skill-grid">{cards}</ul>
</section>""" if by_skill else ""
    filters = ""
    if show_cats():
        chips = "".join(f'<button type="button" data-cat="{k}" aria-pressed="false">{CATEGORIES[k]}</button>' for k in USED)
        filters = f'<div class="filters" role="group" aria-label="Filter posts"><button type="button" data-cat="all" aria-pressed="true">All</button>{chips}</div>'
    body = f"""<section class="wrap blog-hero">
  <p class="eyebrow">Notes</p>
  <h1>Notes from building policymemo.ai</h1>
  <p class="lede">Why policymemo.ai works the way it does, and what changes when the skills do.</p>
</section>
<section class="wrap blog-list" aria-labelledby="latest">
  <div class="list-head"><h2 id="latest">Latest</h2>{filters}</div>
  {latest}
</section>
{series}"""
    return page("Notes · policymemo.ai", "Notes from building policymemo.ai: why it works the way it does, and what changes when the skills do.", body, css, home)


def build_post(p, posts, css, home):
    i = posts.index(p)
    newer = posts[i - 1] if i > 0 else None
    older = posts[i + 1] if i + 1 < len(posts) else None
    nav = ""
    if older or newer:
        nav = '<nav class="pager" aria-label="More posts">' + \
              (f'<a class="prev" href="{older["slug"]}.html"><span>Older</span>{html.escape(older["title"])}</a>' if older else '<span></span>') + \
              (f'<a class="next" href="{newer["slug"]}.html"><span>Newer</span>{html.escape(newer["title"])}</a>' if newer else '<span></span>') + '</nav>'
    # Every post ends one click from trying the product.
    if p.get("skill"):
        name = dict((s[0], s[1]) for s in SKILLS)[p["skill"]]
        pitch = f"The {name} skill is part of policymemo.ai, which is free and in private beta."
    else:
        pitch = "policymemo.ai is free and in private beta. Request access to try it on a problem you're stuck on."
    skill_note = f'<aside class="try"><p>{pitch}</p><a class="btn primary" href="{home}beta/">Request beta access</a></aside>'
    draft = '<p class="draft-flag">Draft · not published</p>' if p["draft"] else ""
    body = f"""<article class="wrap post">
  {draft}<p class="meta"><a href="./">Notes</a> · {cat_label(p, after=" · ")}{nice_date(p['date_obj'])} · {p['minutes']} min read</p>
  <h1>{html.escape(p['title'])}</h1>
  <p class="lede">{html.escape(p['summary'])}</p>
  <div class="prose">{p['body']}</div>
  {skill_note}
  {nav}
</article>"""
    return page(f"{p['title']} · policymemo.ai", p["summary"], body, css, home)


def build_feed(all_posts, title, category):
    """An Atom feed of the published posts, newest first, with full post text."""
    posts = [p for p in all_posts if category is None or p["category"] == category]
    name = "feed-updates.xml" if category else "feed.xml"
    def stamp(d):
        return f"{d.isoformat()}T09:00:00Z"
    # Dated by its newest post, so rebuilding without new posts changes nothing.
    newest = (posts or all_posts)
    updated = stamp(newest[0]["date_obj"] if newest else datetime.date(2026, 10, 1))
    entries = ""
    for p in posts:
        url = f"{SITE}/blog/{p['slug']}.html"
        entries += f"""  <entry>
    <title>{html.escape(p['title'])}</title>
    <link rel="alternate" type="text/html" href="{url}"/>
    <id>{url}</id>
    <published>{stamp(p['date_obj'])}</published>
    <updated>{stamp(p['date_obj'])}</updated>
    <category term="{p['category']}" label="{CATEGORIES[p['category']]}"/>
    <summary>{html.escape(p['summary'])}</summary>
    <content type="html" xml:base="{url}">{html.escape(p['body'])}</content>
  </entry>
"""
    return f"""<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom" xml:lang="en-GB">
  <title>{html.escape(title)}</title>
  <subtitle>Notes from building policymemo.ai.</subtitle>
  <link rel="self" type="application/atom+xml" href="{SITE}/blog/{name}"/>
  <link rel="alternate" type="text/html" href="{SITE}/blog/"/>
  <id>{SITE}/blog/{name}</id>
  <updated>{updated}</updated>
  <author><name>{AUTHOR[0]}</name><email>{AUTHOR[1]}</email></author>
  <icon>{SITE}/favicon.svg</icon>
{entries}</feed>
"""


def build_install(css, home):
    """The install page: one page, one panel per AI tool. Its body is hand-written in site/install/."""
    body = (INSTALL / "body.html").read_text(encoding="utf-8")
    css = css + "\n" + (INSTALL / "install.css").read_text(encoding="utf-8")
    return page("Install · policymemo.ai",
                "Install policymemo.ai in Claude, Microsoft 365 Copilot or Google Gemini. You set it up once, on a computer.",
                body, css, home, current=None)


def beta_config():
    cfg = json.loads((BETA / "config.json").read_text(encoding="utf-8"))
    keys = ("student_form_url", "practitioner_form_url", "access_instructions_url", "support_email", "privacy_url")
    for k in keys:
        if not isinstance(cfg.get(k), str):
            raise SystemExit(f"site/beta/config.json needs '{k}' (an empty string if not set yet)")
        v = cfg[k].strip()
        if k.endswith("_url") and v and not v.startswith("https://"):
            raise SystemExit(f"site/beta/config.json: '{k}' must start with https://")
        if k == "support_email" and v and not re.fullmatch(r"[^@\s\"<>]+@[^@\s\"<>]+\.[^@\s\"<>]+", v):
            raise SystemExit("site/beta/config.json: 'support_email' is not an email address")
        cfg[k] = v
    if not cfg["access_instructions_url"] or not cfg["support_email"]:
        raise SystemExit("site/beta/config.json: 'access_instructions_url' and 'support_email' must be set")
    return cfg


def build_beta(css, home):
    """The beta page: two access routes. A route whose form URL is not set yet shows 'Opening soon'."""
    cfg = beta_config()
    def cta(url, label):
        if not url:
            return '<span class="soon">Opening soon</span>'
        return f'<a class="btn primary" href="{html.escape(url)}">{label}</a>'
    privacy = "We use your email address to manage your access and contact you about the beta. We only send other updates if you ask us to."
    if cfg["privacy_url"]:
        privacy += f' <a href="{html.escape(cfg["privacy_url"])}">How we use your information</a>.'
    fills = {
        "student_cta": cta(cfg["student_form_url"], "Student access"),
        "practitioner_cta": cta(cfg["practitioner_form_url"], "Request beta access"),
        "privacy_line": privacy,
        "access_instructions_url": html.escape(cfg["access_instructions_url"]),
        "support_email": html.escape(cfg["support_email"]),
    }
    body = (BETA / "body.html").read_text(encoding="utf-8")
    body = re.sub(r"\{\{(\w+)\}\}", lambda m: fills[m.group(1)], body)
    css = css + "\n" + (BETA / "beta.css").read_text(encoding="utf-8")
    return page("Private beta · policymemo.ai",
                "policymemo.ai is in private beta, testing with policy students and a small group of practitioners.",
                body, css, home, current="beta")


def build_updates(css, home):
    """The changelog: one Markdown file, newest first."""
    text = re.sub(r"<!--.*?-->", "", CHANGELOG.read_text(encoding="utf-8"), flags=re.S)
    body = f"""<article class="wrap post">
  <p class="meta">Updates</p>
  <h1>What's changed</h1>
  <p class="lede">A plain record of what changed in policymemo.ai, newest first. For the thinking behind the changes, read <a href="{CIVICWORKS_NAV}" target="_blank" rel="noopener">CIVICWORKS</a>.</p>
  <div class="prose">{markdown.markdown(text, extensions=["extra", "smarty"])}</div>
</article>"""
    return page("Updates · policymemo.ai", "What changed in policymemo.ai, release by release.", body, css, home, current="updates")


def update_home(posts):
    s = HOME.read_text(encoding="utf-8")
    live = bool(posts)
    def fill(name, content):
        nonlocal s
        pat = re.compile(r"(<!-- blog:" + re.escape(name) + r" -->).*?(<!-- /blog:" + re.escape(name) + r" -->)", re.S)
        if not pat.search(s):
            raise SystemExit(f"docs/index.html is missing the blog:{name} markers")
        s = pat.sub(lambda m: m.group(1) + content + m.group(2), s)
    fill("civicworks", CIVICWORKS_NAV_LINK)
    fill("footer", '<a href="blog/">Notes</a>' if live else "")
    fill("head", '<link rel="alternate" type="application/atom+xml" title="Notes · policymemo.ai" href="blog/feed.xml">' if live else "")
    by_skill = {p["skill"]: p for p in posts if p.get("skill")}
    for slug, _, _ in SKILLS:
        p = by_skill.get(slug)
        if p:
            link = f'<a class="card-link" href="blog/{p["slug"]}.html">Read the post</a>'
        else:
            link = ""
        fill("card:" + slug, link)
    HOME.write_text(s, encoding="utf-8")


def categories_in_use(posts):
    return [k for k in CATEGORIES if any(p["category"] == k for p in posts)]


def main():
    global USED
    drafts_out = None
    if len(sys.argv) == 3 and sys.argv[1] == "--drafts":
        drafts_out = pathlib.Path(sys.argv[2])
    all_posts = sorted((read_post(f) for f in POSTS.glob("*.md")), key=lambda p: p["date_obj"], reverse=True)
    css = CSS.read_text(encoding="utf-8")
    if drafts_out:
        USED = categories_in_use(all_posts)
        drafts_out.mkdir(parents=True, exist_ok=True)
        (drafts_out / "index.html").write_text(build_index(all_posts, css, "../"), encoding="utf-8")
        for p in all_posts:
            (drafts_out / f"{p['slug']}.html").write_text(build_post(p, all_posts, css, "../"), encoding="utf-8")
        print(f"preview with drafts: {len(all_posts)} posts in {drafts_out}")
        return 0
    posts = [p for p in all_posts if not p["draft"]]
    USED = categories_in_use(posts)
    OUT.mkdir(parents=True, exist_ok=True)
    for f in OUT.glob("*.html"):
        if GENERATED in f.read_text(encoding="utf-8"):
            f.unlink()
    (OUT / "index.html").write_text(build_index(posts, css, "../"), encoding="utf-8")
    for p in posts:
        (OUT / f"{p['slug']}.html").write_text(build_post(p, posts, css, "../"), encoding="utf-8")
    for name, title, category in FEEDS:
        if category and category not in USED:
            (OUT / name).unlink(missing_ok=True)
            continue
        (OUT / name).write_text(build_feed(posts, title, category), encoding="utf-8")
    update_home(posts)
    INSTALL_OUT.mkdir(parents=True, exist_ok=True)
    (INSTALL_OUT / "index.html").write_text(build_install(css, "../"), encoding="utf-8")
    BETA_OUT.mkdir(parents=True, exist_ok=True)
    (BETA_OUT / "index.html").write_text(build_beta(css, "../"), encoding="utf-8")
    UPDATES_OUT.mkdir(parents=True, exist_ok=True)
    (UPDATES_OUT / "index.html").write_text(build_updates(css, "../"), encoding="utf-8")
    print(f"{len(posts)} published, {len(all_posts) - len(posts)} draft(s) held back")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
