#!/usr/bin/env python3
"""Build the policymemo.ai blog from Markdown.

Posts live in blog/posts/*.md, each with a short front matter block:

    ---
    title: Why policymemo.ai asks before it writes
    date: 2026-10-06
    category: why            # why | skills | guides | updates
    skill: problem           # only for posts in the skills series
    summary: One sentence for the index and for link previews.
    draft: true              # optional; drafts are never published
    ---

This writes docs/blog/index.html and one docs/blog/<slug>.html per published
post (the slug is the file name), plus two Atom feeds: feed.xml (every post)
and feed-updates.xml (product updates only). It also updates the homepage between its
blog markers: a Blog link in the nav and footer, and a "Read the post" link on
each skill card, all of which stay empty until something is published, so the
site never shows an empty blog.

    python3 tools/build-blog.py              # publish
    python3 tools/build-blog.py --drafts OUT # preview everything, drafts included, into OUT

Requires the `markdown` package (pip install markdown).
"""
import datetime
import html
import pathlib
import re
import sys

import markdown

ROOT = pathlib.Path(__file__).resolve().parent.parent
POSTS = ROOT / "blog" / "posts"
CSS = ROOT / "blog" / "blog.css"
OUT = ROOT / "docs" / "blog"
HOME = ROOT / "docs" / "index.html"
INSTALL = ROOT / "install"
INSTALL_OUT = ROOT / "docs" / "install"
ICONS = ROOT / "docs" / "icons"
MASCOT = ROOT / "docs" / "mascot.svg"
LATEST = ""  # date of the newest published post; drives the "new" dot by Notes on the homepage
GENERATED = "<!-- generated by tools/build-blog.py; edit blog/posts or the script, not this file -->"

CATEGORIES = {"why": "Why it works", "skills": "The skills", "guides": "Guides", "updates": "Updates"}
# Skill slug, card title on the homepage, icon file.
SKILLS = [
    ("problem", "Problem", "problem"), ("stakeholders", "Stakeholders", "stakeholders"),
    ("evidence", "Evidence", "evidence"), ("options", "Options", "options"),
    ("criteria", "Criteria", "criteria"), ("outcomes", "Outcomes", "uncertainty"),
    ("trade-offs", "Trade-offs", "tradeoffs"), ("decide", "Decide", "decision"),
    ("story", "Story", "story"),
]
FEEDBACK = "mailto:jack@civicworks.co?subject=policymemo.ai%20feedback"
SITE = "https://policymemo.ai"
AUTHOR = ("Jack Strachan", "jack@civicworks.co")
# Email sign-up. Set to the Buttondown username once the newsletter exists; the form
# stays off the site until then. Buttondown sends an email for each new post in feed.xml.
BUTTONDOWN = ""
FEEDS = [("feed.xml", "Notes · policymemo.ai", None),
         ("feed-updates.xml", "Product updates · policymemo.ai", "updates")]


def read_post(path):
    text = path.read_text(encoding="utf-8")
    m = re.match(r"---\n(.*?)\n---\n(.*)", text, re.S)
    if not m:
        raise SystemExit(f"{path.name}: missing front matter")
    meta = {}
    for line in m.group(1).splitlines():
        if ":" in line:
            k, v = line.split(":", 1)
            meta[k.strip()] = v.split(" #", 1)[0].strip()
    for key in ("title", "date", "category", "summary"):
        if not meta.get(key):
            raise SystemExit(f"{path.name}: front matter needs '{key}'")
    if meta["category"] not in CATEGORIES:
        raise SystemExit(f"{path.name}: category must be one of {', '.join(CATEGORIES)}")
    if meta.get("skill") and meta["skill"] not in {s[0] for s in SKILLS}:
        raise SystemExit(f"{path.name}: unknown skill '{meta['skill']}'")
    meta["date_obj"] = datetime.date.fromisoformat(meta["date"])
    meta["draft"] = meta.get("draft", "").lower() == "true"
    meta["slug"] = path.stem
    meta["body"] = markdown.markdown(m.group(2), extensions=["extra", "smarty"])
    words = len(re.sub(r"<[^>]+>", " ", meta["body"]).split())
    meta["minutes"] = max(1, round(words / 220))
    return meta


def nice_date(d):
    return f"{d.day} {d.strftime('%B %Y')}"


def svg_inline(path, cls, prefix):
    s = path.read_text(encoding="utf-8")
    s = re.sub(r"<\?xml.*?\?>", "", s).strip()
    s = re.sub(r"<title>.*?</title>", "", s)
    s = s.replace('id="pm-', f'id="{prefix}').replace("url(#pm-", f"url(#{prefix}")
    return s.replace("<svg ", f'<svg class="{cls}" aria-hidden="true" ', 1)


def page(title, description, body, css, home, depth_note="", current="notes"):
    notes_current = ' aria-current="page"' if current == "notes" else ""
    mascot = svg_inline(MASCOT, "logo", "lg-").replace('fill="#1c1b18"', 'fill="currentColor"')
    return f"""<!doctype html>
{GENERATED}
<html lang="en-GB">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="color-scheme" content="light">
<title>{html.escape(title)}</title>
<meta name="description" content="{html.escape(description)}">
<meta property="og:title" content="{html.escape(title)}">
<meta property="og:description" content="{html.escape(description)}">
<meta property="og:image" content="https://policymemo.ai/og.png">
<meta name="twitter:card" content="summary_large_image">
<link rel="icon" href="{home}favicon.svg" type="image/svg+xml">
<link rel="alternate" type="application/atom+xml" title="Notes · policymemo.ai" href="{home}blog/feed.xml">
<link rel="alternate" type="application/atom+xml" title="Product updates · policymemo.ai" href="{home}blog/feed-updates.xml">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght,SOFT@9..144,300..600,0..100&family=Geist:wght@400..600&display=swap" rel="stylesheet">
<style>
{css}
</style>
</head>
<body>
<header class="top">
  <div class="wrap bar">
    <a class="brand" href="{home}" aria-label="policymemo.ai home">{mascot}</a>
    <nav aria-label="Main">
      <a class="plain" href="{home}#what">What it does</a>
      <a class="plain keep" href="{home}blog/"{notes_current} data-latest="{LATEST}">Notes</a>
      <a class="plain keep" href="{FEEDBACK}">Feedback</a>
      <a class="btn primary small" href="{home}install/">Download</a>
    </nav>
  </div>
</header>
<main>
{body}
</main>
<footer>
  <div class="wrap row">
    <span>policymemo.ai · beta 0.1.2</span>
    <nav aria-label="Footer">
      <a href="{home}">Home</a>
      <a href="{home}install/">Install</a>
      <a href="{FEEDBACK}">Feedback</a>
      <a href="{home}blog/feed.xml">RSS</a>
      <a href="https://github.com/Policy-Analysis-Tools-for-Everyone/Alpha">GitHub</a>
    </nav>
  </div>
</footer>
<script>
(function () {{
  var n = document.querySelector('[data-latest]');
  try {{ if (n && n.getAttribute('data-latest')) localStorage.setItem('pm-notes-seen', n.getAttribute('data-latest')); }} catch (e) {{}}
  var reduce = window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  var els = Array.prototype.slice.call(document.querySelectorAll('[data-rise]'));
  if (reduce || !('IntersectionObserver' in window)) return;
  els.forEach(function (el) {{ if (el.getBoundingClientRect().top > window.innerHeight) el.classList.add('pre'); }});
  var io = new IntersectionObserver(function (es) {{
    es.forEach(function (e, k) {{ if (e.isIntersecting) {{ io.unobserve(e.target); setTimeout(function () {{ e.target.classList.remove('pre'); }}, k * 90); }} }});
  }}, {{ threshold: 0.2 }});
  els.forEach(function (el) {{ io.observe(el); }});
  var chips = Array.prototype.slice.call(document.querySelectorAll('.filters button'));
  chips.forEach(function (c) {{
    c.addEventListener('click', function () {{
      var cat = c.getAttribute('data-cat');
      chips.forEach(function (x) {{ x.setAttribute('aria-pressed', x === c ? 'true' : 'false'); }});
      document.querySelectorAll('.post-row').forEach(function (r) {{ r.hidden = cat !== 'all' && r.getAttribute('data-cat') !== cat; }});
    }});
  }});
}})();
</script>
</body>
</html>
"""


def build_index(posts, css, home):
    by_skill = {p["skill"]: p for p in posts if p.get("skill")}
    rows = "".join(
        f'<li class="post-row" data-cat="{p["category"]}" data-rise><a href="{p["slug"]}.html">'
        f'<span class="meta"><span class="cat">{CATEGORIES[p["category"]]}</span> · {nice_date(p["date_obj"])}</span>'
        f'<span class="t">{html.escape(p["title"])}</span><span class="s">{html.escape(p["summary"])}</span></a></li>'
        for p in posts)
    latest = (f'<ul class="posts">{rows}</ul>' if posts else
              '<p class="empty">The first post is on its way. In the meantime, <a href="' + home + '">see what policymemo.ai does</a>.</p>')
    cards = ""
    for slug, title, icon in SKILLS:
        p = by_skill.get(slug)
        art = svg_inline(ICONS / f"{icon}.svg", "icon", f"sk-{slug}-")
        status = (f'<a class="read" href="{p["slug"]}.html">Read · {nice_date(p["date_obj"])}</a>' if p
                  else '<span class="soon">Coming soon</span>')
        cards += f'<li class="{"live" if p else "planned"}" data-rise>{art}<h3>{title}</h3>{status}</li>'
    signup = (f'<form class="signup" action="https://buttondown.com/api/emails/embed-subscribe/{BUTTONDOWN}" method="post">'
              '<label for="signup-email">Get each new post by email</label>'
              '<div class="field"><input id="signup-email" type="email" name="email" placeholder="you@example.org" autocomplete="email" required>'
              '<button class="btn primary small" type="submit">Subscribe</button></div>'
              '<p class="fine">One email per post. Unsubscribe from any of them.</p></form>' if BUTTONDOWN else "")
    follow = f"""<section class="wrap follow" aria-labelledby="follow" data-rise>
  <h2 id="follow">Follow along</h2>
  {signup}<p class="feeds">Or use a feed reader: <a href="feed.xml">every post</a> or <a href="feed-updates.xml">product updates only</a>.</p>
</section>"""
    filters = "".join(f'<button type="button" data-cat="{k}" aria-pressed="false">{v}</button>' for k, v in CATEGORIES.items())
    body = f"""<section class="wrap blog-hero">
  <p class="eyebrow">Notes</p>
  <h1>Notes from building policymemo.ai</h1>
  <p class="lede">Why it works the way it does, a post on each skill as the course runs, and what changes when the skills do.</p>
</section>
<section class="wrap blog-list" aria-labelledby="latest">
  <div class="list-head"><h2 id="latest">Latest</h2>
    <div class="filters" role="group" aria-label="Filter posts"><button type="button" data-cat="all" aria-pressed="true">All</button>{filters}</div></div>
  {latest}
</section>
<section class="wrap series" aria-labelledby="series">
  <h2 id="series">One post for each skill</h2>
  <p class="intro">Each post covers what the skill does, the method behind it, and what it looks like on a real problem.</p>
  <ul class="skill-grid">{cards}</ul>
</section>
{follow}"""
    return page("Notes · policymemo.ai", "Notes from building policymemo.ai: why it works the way it does, a post on each skill, and what changes.", body, css, home)


def build_post(p, posts, css, home):
    i = posts.index(p)
    newer = posts[i - 1] if i > 0 else None
    older = posts[i + 1] if i + 1 < len(posts) else None
    nav = ""
    if older or newer:
        nav = '<nav class="pager" aria-label="More posts">' + \
              (f'<a class="prev" href="{older["slug"]}.html"><span>Older</span>{html.escape(older["title"])}</a>' if older else '<span></span>') + \
              (f'<a class="next" href="{newer["slug"]}.html"><span>Newer</span>{html.escape(newer["title"])}</a>' if newer else '<span></span>') + '</nav>'
    # Every post ends one click from trying the product.
    if p.get("skill"):
        name = dict((s[0], s[1]) for s in SKILLS)[p["skill"]]
        pitch = f"The {name} skill is part of policymemo.ai, which is free."
    else:
        pitch = "Try policymemo.ai on a problem you're stuck on. It's free."
    skill_note = f'<aside class="try"><p>{pitch}</p><a class="btn primary" href="{home}install/">Download it</a></aside>'
    draft = '<p class="draft-flag">Draft · not published</p>' if p["draft"] else ""
    body = f"""<article class="wrap post">
  {draft}<p class="meta"><a href="./">Notes</a> · <span class="cat">{CATEGORIES[p['category']]}</span> · {nice_date(p['date_obj'])} · {p['minutes']} min read</p>
  <h1>{html.escape(p['title'])}</h1>
  <p class="lede">{html.escape(p['summary'])}</p>
  <div class="prose">{p['body']}</div>
  {skill_note}
  {nav}
</article>"""
    return page(f"{p['title']} · policymemo.ai", p["summary"], body, css, home)


def build_feed(all_posts, title, category):
    """An Atom feed of the published posts, newest first, with full post text."""
    posts = [p for p in all_posts if category is None or p["category"] == category]
    name = "feed-updates.xml" if category else "feed.xml"
    def stamp(d):
        return f"{d.isoformat()}T09:00:00Z"
    # Dated by its newest post, so rebuilding without new posts changes nothing.
    newest = (posts or all_posts)
    updated = stamp(newest[0]["date_obj"] if newest else datetime.date(2026, 10, 1))
    entries = ""
    for p in posts:
        url = f"{SITE}/blog/{p['slug']}.html"
        entries += f"""  <entry>
    <title>{html.escape(p['title'])}</title>
    <link rel="alternate" type="text/html" href="{url}"/>
    <id>{url}</id>
    <published>{stamp(p['date_obj'])}</published>
    <updated>{stamp(p['date_obj'])}</updated>
    <category term="{p['category']}" label="{CATEGORIES[p['category']]}"/>
    <summary>{html.escape(p['summary'])}</summary>
    <content type="html" xml:base="{url}">{html.escape(p['body'])}</content>
  </entry>
"""
    return f"""<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom" xml:lang="en-GB">
  <title>{html.escape(title)}</title>
  <subtitle>Notes from building policymemo.ai.</subtitle>
  <link rel="self" type="application/atom+xml" href="{SITE}/blog/{name}"/>
  <link rel="alternate" type="text/html" href="{SITE}/blog/"/>
  <id>{SITE}/blog/{name}</id>
  <updated>{updated}</updated>
  <author><name>{AUTHOR[0]}</name><email>{AUTHOR[1]}</email></author>
  <icon>{SITE}/favicon.svg</icon>
{entries}</feed>
"""


def build_install(css, home):
    """The install page: one page, one panel per AI tool. Its body is hand-written in install/."""
    body = (INSTALL / "body.html").read_text(encoding="utf-8")
    css = css + "\n" + (INSTALL / "install.css").read_text(encoding="utf-8")
    return page("Install · policymemo.ai",
                "Install policymemo.ai in Claude, Microsoft 365 Copilot or Google Gemini. You set it up once, on a computer.",
                body, css, home, current=None)


def update_home(posts):
    s = HOME.read_text(encoding="utf-8")
    live = bool(posts)
    def fill(name, content):
        nonlocal s
        pat = re.compile(r"(<!-- blog:" + re.escape(name) + r" -->).*?(<!-- /blog:" + re.escape(name) + r" -->)", re.S)
        if not pat.search(s):
            raise SystemExit(f"docs/index.html is missing the blog:{name} markers")
        s = pat.sub(lambda m: m.group(1) + content + m.group(2), s)
    fill("nav", f'<a class="plain keep notes-link" href="blog/" data-latest="{posts[0]["date_obj"].isoformat()}">Notes<span class="new-dot" aria-hidden="true"></span></a>' if live else "")
    fill("footer", '<a href="blog/">Notes</a><a href="blog/feed.xml">RSS</a>' if live else "")
    fill("head", '<link rel="alternate" type="application/atom+xml" title="Notes · policymemo.ai" href="blog/feed.xml">' if live else "")
    by_skill = {p["skill"]: p for p in posts if p.get("skill")}
    for slug, _, _ in SKILLS:
        p = by_skill.get(slug)
        fill("card:" + slug, f'<a class="card-link" href="blog/{p["slug"]}.html">Read the post</a>' if p else "")
    HOME.write_text(s, encoding="utf-8")


def main():
    drafts_out = None
    if len(sys.argv) == 3 and sys.argv[1] == "--drafts":
        drafts_out = pathlib.Path(sys.argv[2])
    all_posts = sorted((read_post(f) for f in POSTS.glob("*.md")), key=lambda p: p["date_obj"], reverse=True)
    css = CSS.read_text(encoding="utf-8")
    if drafts_out:
        drafts_out.mkdir(parents=True, exist_ok=True)
        (drafts_out / "index.html").write_text(build_index(all_posts, css, "../"), encoding="utf-8")
        for p in all_posts:
            (drafts_out / f"{p['slug']}.html").write_text(build_post(p, all_posts, css, "../"), encoding="utf-8")
        print(f"preview with drafts: {len(all_posts)} posts in {drafts_out}")
        return 0
    posts = [p for p in all_posts if not p["draft"]]
    global LATEST
    LATEST = posts[0]["date_obj"].isoformat() if posts else ""
    OUT.mkdir(parents=True, exist_ok=True)
    for f in OUT.glob("*.html"):
        if GENERATED in f.read_text(encoding="utf-8"):
            f.unlink()
    (OUT / "index.html").write_text(build_index(posts, css, "../"), encoding="utf-8")
    for p in posts:
        (OUT / f"{p['slug']}.html").write_text(build_post(p, posts, css, "../"), encoding="utf-8")
    for name, title, category in FEEDS:
        (OUT / name).write_text(build_feed(posts, title, category), encoding="utf-8")
    update_home(posts)
    INSTALL_OUT.mkdir(parents=True, exist_ok=True)
    (INSTALL_OUT / "index.html").write_text(build_install(css, "../"), encoding="utf-8")
    print(f"{len(posts)} published, {len(all_posts) - len(posts)} draft(s) held back")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
